SP_HELP RESULTADOFASE

ALTER TABLE RESULTADOFASE
DROP CONSTRAINT TREINAMENTO_RESULTADO_fk;

ALTER TABLE RESULTADOFASE
DROP COLUMN treinamentofaseIDtreinamentofase;

ALTER TABLE TREINAMENTOFASE
ADD     exercicioIdExercicio        INT,
        resultadoTreino             FLOAT,
        resultadoIDresultadoFase    INT;

ALTER TABLE TREINAMENTOFASE
DROP COLUMN resultadoTREINO



SELECT * FROM PARAMETRO


DELETE PARAMETRO
WHERE idParametro >= 8


SELECT * FROM USUARIO

DELETE USUARIO
WHERE idUsuario >= 19


SELECT * FROM FASE


ALTER TABLE FASE
DROP CONSTRAINT PARAMETRO_FASE_fk;
GO
ALTER TABLE FASE
DROP COLUMN parametroIDparametro;
GO

SELECT * FROM PACIENTE

SELECT * FROM TIPOUSUARIO


ALTER TABLE RESULTADOFASE
ALTER COLUMN resultadoFase FLOAT NULL
ADD qtdeResultadoFase INT NULL;